[package]
name = "ln-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.3.2"
scraper = "0.12.0"
tokio = { version = "1.17.0", features = ["full"] }
